/** @type {import('prettier').Config} */
module.exports = {
    endOfLine: 'lf',
    semi: false,
    singleQuote: true,
    tabWidth: 2,
    importOrder: [
        '^(react/(.*)$)|^(react$)',
        '^(next/(.*)$)|^(next$)',
        '<THIRD_PARTY_MODULES>',
        '',
        '^@/hooks',
        '^@/hooks/(.*)$',
        '^@/components/ui/(.*)$',
        '^@/components/(.*)$',
        '^@/app/(.*)$',
        '^@/pages/(.*)$',
        '^@/stores$',
        '^@/stores/(.*)$',
        '^@/contexts$',
        '^@/contexts/(.*)$',
        '^@/graphql$',
        '^@/graphql/(.*)$',
        '^@/queries$',
        '^@/queries/(.*)$',
        '^@/types$',
        '^@/types/(.*)$',
        '^@/constant$',
        '^@/constant/(.*)$',
        '^@/config$',
        '^@/config/(.*)$',
        '^@/lib/(.*)$',
        '^@/utils$',
        '^@/utils/(.*)$',
        '^@/typedABI$',
        '^@/typedABI/(.*)$',
        '',
        '^@/public$',
        '^@/public/(.*)$',
        '^@/styles/(.*)$',
        '',
        '^[./]',
    ],
    importOrderSeparation: false,
    importOrderSortSpecifiers: true,
    importOrderBuiltinModulesToTop: true,
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
    importOrderMergeDuplicateImports: true,
    importOrderCombineTypeAndValueImports: true,
    plugins: ['@ianvs/prettier-plugin-sort-imports'],
};